// VFX pool sizes + tracer / smoke / shell / decal tuning.
// Values moved verbatim from BulletTracer + DecalManager.

export const EFFECTS = {
  MAX_TRACERS: 24,
  MAX_SMOKE: 32,
  MAX_SHELLS: 30,
  MAX_DECALS: 40,
  MAX_SPARKS: 60,
  TRACER_SPEED: 320,
  TRACER_LIFE_S: 0.35,
  TRACER_MIN_DIST: 0.1,
  SMOKE_SCALE: 0.08,
  SMOKE_OPACITY: 0.5,
  SMOKE_LIFE_S: 0.28,
  SMOKE_RISE_BASE: 0.35,
  SMOKE_RISE_RANDOM: 0.25,
  SMOKE_SPREAD: 0.3,
  FLASH_LIGHT_RIFLE_INTENSITY: 55,
  DECAL_FADE_S: 8,
} as const;

export const MUZZLE_FLASH = {
  RIFLE_PLANE: 0.34,
  RIFLE_CONE_W: 0.38,
  RIFLE_CONE_H: 0.24,
  RIFLE_CONE_Z: -0.07,
  PISTOL_PLANE: 0.12,
  LIGHT_RIFLE_COLOR: 0xffb74d,
  LIGHT_RIFLE_DISTANCE: 12,
  LIGHT_PISTOL_COLOR: 0xff9944,
  LIGHT_PISTOL_DISTANCE: 5,
  FLASH_TEXTURE_RIFLE: 256,
  FLASH_TEXTURE_PISTOL: 128,
  TRACER_TEXTURE: 256,
  SMOKE_TEXTURE: 128,
} as const;
