// Weapon definitions + recoil / ADS / swap tuning.
// Offsets stored as tuples so this file stays side-effect free
// (no `new THREE.Vector3` here). Build Vector3s at the call site.
// Values moved verbatim from WeaponManager — do not retune here.

export const WEAPON_DEFS = [
  {
    name: 'AK-47',
    fireMode: 'AUTO // 7.62x39mm',
    isAuto: true,
    fireRate: 10.0,
    magSize: 30,
    startAmmo: 30,
    reserveAmmo: 120,
    damage: 48,
    idleOffset: [0.25, -0.285, -0.19] as const,
    adsOffset: [0.0, -0.125, -0.03] as const,
    recoilForce: {
      posZ: 0.052,
      rotX: 0.08,
      camPitch: 0.026,
      camYaw: 0.012,
      spray: 'ak',
    } as const,
    reloadTime: 2.0,
    reloadStyle: 'mag' as const,
  },
  {
    name: 'TACTICAL GHOST',
    fireMode: 'SEMI // 9x19mm SUPPRESSED',
    isAuto: false,
    fireRate: 7.0,
    magSize: 15,
    startAmmo: 15,
    reserveAmmo: 60,
    damage: 36,
    idleOffset: [0.15, -0.125, -0.24] as const,
    adsOffset: [0.0, -0.055, -0.18] as const,
    recoilForce: {
      posZ: 0.038,
      rotX: 0.06,
      camPitch: 0.014,
      camYaw: 0.005,
      spray: 'simple',
    } as const,
    reloadTime: 1.9,
    reloadStyle: 'mag' as const,
  },
  {
    name: 'BREACHER 12G',
    fireMode: 'PUMP // 12 GAUGE BUCK',
    isAuto: false,
    fireRate: 1.2,
    magSize: 6,
    startAmmo: 6,
    reserveAmmo: 30,
    damage: 22,
    idleOffset: [0.2, -0.26, -0.24] as const,
    adsOffset: [0.0, -0.075, -0.1] as const,
    recoilForce: {
      posZ: 0.085,
      rotX: 0.14,
      camPitch: 0.085,
      camYaw: 0.018,
      spray: 'simple',
    } as const,
    reloadTime: 2.8,
    reloadStyle: 'shells' as const,
    pellets: 8,
    pelletSpread: 0.055,
  },
] as const;

export type WeaponDefIndex = 0 | 1 | 2;
export type ReloadStyle = (typeof WEAPON_DEFS)[number]['reloadStyle'];
export type SprayKind = (typeof WEAPON_DEFS)[number]['recoilForce']['spray'];

export const WEAPONS = {
  BURST_RESET_S: 0.35,
  SWAP_HOLSTER_S: 0.12,
  SWAP_EQUIP_S: 0.36,
  HIP_FOV: 75,
  ADS_FOV: 48,
  ADS_LERP_RATE: 14,
  RECOIL_STIFFNESS: 240,
  RECOIL_DAMPING: 20,
  CAMERA_RECOIL_LERP_RATE: 16,
  BOB_RATE: 11.0,
  BOB_MOVE_THRESHOLD: 0.5,
  BOB_X_HIP: 0.012,
  BOB_X_ADS: 0.001,
  BOB_Y_HIP: 0.016,
  BOB_Y_ADS: 0.002,
  VIEWMODEL_LERP_HIP: 12,
  VIEWMODEL_LERP_ADS: 20,
  KICK_HIP_MULT: 1.0,
  KICK_ADS_MULT: 0.75,
  ADS_PITCH_MULT: 0.55,
  ESCALATE_PER_SHOT: 0.11,
  ESCALATE_MAX_SHOTS: 9,
  POS_Z_TO_VEL: 4.4,
  POS_Z_TO_LIFT: 1.3,
  ROT_X_TO_VEL: 5.2,
  ROLL_RANDOM: 0.08,
  YAW_RANDOM: 0.05,
  PITCH_RANDOM_MIN: 0.88,
  PITCH_RANDOM_SPAN: 0.24,
  AK_SNAKE_START: 5,
  AK_SNAKE_FREQ: 0.85,
  AK_SNAKE_AMP: 1.9,
  AK_SNAKE_RANDOM: 0.5,
  AK_PITCH_DAMP_FROM_SHOT: 6,
  AK_PITCH_DAMP_MULT: 0.78,
  SLIDE_KICK_Z: 0.038,
  FLASH_HIP_SCALE: 1.05,
  FLASH_ADS_SCALE: 0.72,
  FLASH_RANDOM_MIN: 0.9,
  FLASH_RANDOM_SPAN: 0.3,
  FLASH_LIGHT_INTENSITY: 55,
  FLASH_DURATION_S: 0.042,
  SPREAD_X_HIP: 0.8,
  SPREAD_X_ADS: 0.25,
  SPREAD_Y_HIP: 1.1,
  SPREAD_Y_ADS: 0.35,
  SPREAD_YAW_TO_TELEMETRY: 12,
  SPREAD_PITCH_TO_TELEMETRY: 16,
  MISS_RAY_DISTANCE: 80,
  STANCE_KICK_PRONE: 0.5,
  STANCE_KICK_CROUCH: 0.75,
  STANCE_KICK_STAND: 1,
  HITMARKER_MS: 120,
  HITMARKER_HEADSHOT_MS: 180,
  HUD_SPREAD_FIRE_MS: 120,
  HUD_SPREAD_SHOT_MS: 75,
} as const;

export const RELOAD_CUES = {
  SHELLS_FEED_START: 0.18,
  SHELLS_FEED_END: 0.82,
  SHELLS_RACK_T: 0.88,
  SHELL_CUE_STEP: 0.6,
  SHELL_CUE_BASE: 0.2,
  MAG_RELEASE_T: 0.02,
  MAG_OUT_T: 0.2,
  MAG_IN_T: 0.6,
  BOLT_RACK_T: 0.82,
} as const;
